### ISSUE TITLE
关于深色模式适配的问题

### ISSUE THREAD

**Issue by CCKNBC** [YunYouJun/hexo-widget-tree#3]
目前来讲按钮在深色模式几乎就是纯白，展开后也不用说了，希望能自适应深色模式浅色模式切换

关于配置项，那个目录满吸引我的，开启了pjax虽然能做到无刷新页面，但是通过点击页面获取到的目录展开的文章不对的（或者说是不会变），只有通过这个侧边栏才能正常显示，除非刷新（或者说是关闭pjax）

**Comment by YunYouJun** [comment]
深色模式切换，之后会考虑实现。

后面一条 PJAX 所指的是什么？可以截图或者更详细地描述吗？

**Comment by CCKNBC** [comment]
这个等我明天再说吧 一开始用的就是 yun 主题， 现在用的 butterfly ，但又想换回云（大概就是折腾后看明白了，除了外挂标签带着适配过来应该没啥了） 而且对于手机端这个宽度的原因导致蝴蝶不能看到收回按钮
下午发了一个版本
https://github.com/CCKNBC/ccknbc.github.io/commit/d5e0448581fbb7854f5e4c88f5f67ffff0653764

**Comment by CCKNBC** [comment]
配置如下 因为主题不是 layout 所以只能选默认的全部显示
```yaml
widget_tree:
  cdn: true
  hide: fasle
  layout: default
  # layout:
  #   - home
  #   - page
  #   - post
  #   - archive
  #   - category
  #   - tag
  toc:
    enable: true
    max_depth: 
    min_depth: 
    list_number: true
```

对于 pjax 我昨天是把整个 div 排除来解决
```pug
script(src=url_for(theme.CDN.pjax))
script.
  let pjaxSelectors = [
    'title',
    '#config_change',
    '#body-wrap',
    '#rightside-config-hide',
    '#rightside-config-show',
    '#posts-chart',
    '#tags-chart',
    '#categories-chart',  
    '#artitalk_main',
    '#app',
    'widget-tree',
    '.js-pjax'
  ]
```
今天发现应该是我文章本身的问题，其他文章目录都正常，只是我昨天恰巧选了这一篇
![QQ截图20210111135623](https://user-images.githubusercontent.com/62093618/104150661-91143880-5415-11eb-90d6-bcd40f12177f.png)

![QQ截图20210111135955](https://user-images.githubusercontent.com/62093618/104150618-6c1fc580-5415-11eb-9b19-2c9ae187ab93.png)

不过手机上因为主题原因不能显示收回按钮
![QQ截图20210111140301](https://user-images.githubusercontent.com/62093618/104150761-e2bcc300-5415-11eb-8268-a4bb73ddb03c.png)

**Comment by YunYouJun** [comment]
宽度是 `20rem`，一般 1rem 是 16px，20 也应该只有 `320px`，手机设备应该是大于这个宽度的。试试别的设备？

**Comment by YunYouJun** [comment]
已支持暗色模式 https://github.com/YunYouJun/hexo-widget-tree/commit/95b36b121fec66c99fbb0d3f42cd170df7c4a0e8

**Comment by CCKNBC** [comment]
因为我用我手机测的不显示 电脑上换也没几个能完全显示的

**Comment by CCKNBC** [comment]
> 已支持暗色模式 [95b36b1](https://github.com/YunYouJun/hexo-widget-tree/commit/95b36b121fec66c99fbb0d3f42cd170df7c4a0e8。)

好评 这就试试 其实就是这个目录吸引了我 想把目录放在左侧 但不想改源码 这个插件简直爱了爱了（分类页面实在有点丑，插件来弥补）

**Comment by YunYouJun** [comment]
> 因为我用我手机测的不显示 电脑上换也没几个能完全显示的

我这边测试，无法复现。我主题的侧边栏也是 `20rem` 宽，访问我的 [主页](https://www.yunyoujun.cn) 打开侧边栏是否同样遮挡住全部内容？

能想到的解决方案是侧边栏添加额外的关闭按钮。

**Comment by CCKNBC** [comment]
你的demo页面是ok的，我再测试看看

**Comment by YunYouJun** [comment]
Chrome 400*670 分辨率测试。

![image](https://user-images.githubusercontent.com/25154432/104152304-21ed1300-541a-11eb-8d34-8994794791f5.png)

**Comment by YunYouJun** [comment]
> 你的demo页面是ok的，我再测试看看

那可能是由于主题样式覆盖导致的，可以通过自定义 CSS 等方式重置浏览器默认 rem 尺寸。

```css
html {
  font-size: 16px;
}
```
